### ISSUE TITLE
Obfuscation failed for dnscat2

### ISSUE THREAD

**Issue by network23** [jaredhaight/PSAttackBuildTool#13]
> Stage: Processing Modules
Status: ERROR!!
 Obfuscation failed for c:\users\user\AppData\Romaing\PSAttackBuildTool\ModuleSrc\Luke  Bagget - dnscat2.ps1.ps

This is with the release downloaded from Github and when manually compiled.
Virtualbox VM: Windows 7 64bit.
I removed the PSAttackBuildTool folder from Appdata\Roaming before running the tool again.

**Comment by jaredhaight** [comment]
Yeah.. thats expected for now. Something about dnscat2 doesn't play nice with Invoke-Obfuscation. When I have more time I'll try and find some option in Invoke-Obfuscation that works for dnscat2.

**Comment by network23** [comment]
Is it possible to build without dnscat2?
Does A/V detect dnscat as malicious? I uploaded it to Virustotal and only MalwarePatrol says it malicious.

Thanks for the reply and your great work Jared.

**Comment by jaredhaight** [comment]
Naw, AMSI doesn't have a signature for dnscat2. You can remove it modules.json to prevent it form being bundled during the build.
