### ISSUE TITLE
There was an error processing ...

### ISSUE THREAD

**Issue by whoot** [jaredhaight/PSAttackBuildTool#14]
Hey,

when running the PSAttackBuildTool.exe I get various index errors like:

![grafik](https://user-images.githubusercontent.com/8066322/34980294-574cc3c4-faa4-11e7-946a-b1ef8d78965c.png)

(translation to englisch is something like: Index is out of bounds. It cant be negative or lower than the collection.)

I get the same error not only for Powersploit, but every other module, too.

**Comment by Snefrou** [comment]
Hello mate ! have you been able to resolve the issue, i'm having the exact same thing

**Comment by sdcampbell** [comment]
I'm having the same issue.

**Comment by whoot** [comment]
Nope, did not further investigate, sorry

**Comment by jaredhaight** [comment]
I just pushed a new version of the build tool, can you give that a shot and let me know if you're still having issues?

https://github.com/jaredhaight/PSAttackBuildTool/releases/latest

If you are, can you let me know what version of Windows you're using?

**Comment by whoot** [comment]
having a different issue now. When running the exe i get:
```
Stage: Getting PS>Attack
 Status: Searching Github
Unbehandelte Ausnahme: System.Net.WebException: Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei PSAttackBuildTool.Utils.PSABTUtils.GetPSAttack()
   bei PSAttackBuildTool.Program.Main(String[] args)
``

which means that it is not possible to open a secure SSL/TLS channel.
Im using Windows 10.

**Comment by network23** [comment]
I have the the same error @ Windows 7 virtual machine.
It's possible to ping github.


```
 Stage: Getting PS>Attack
 Status: Searching Github
Unhandled Exception: System.Net.WebException: The request was aborted: Could not
 create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request
)
   at System.Net.WebClient.DownloadString(Uri address)
   at PSAttackBuildTool.Utils.PSABTUtils.GetPSAttack()
   at PSAttackBuildTool.Program.Main(String[] args)
```

**Comment by Lyes06** [comment]
Same Issue..

**Comment by jaredhaight** [comment]
Closing this ticket. The SSL issue is being tracked in issue #18
